-- This script was generated by the ERD tool in pgAdmin 4.
CREATE TABLE IF NOT EXISTS public.actividades (
    id_activity serial NOT NULL,
    activity_name character varying COLLATE pg_catalog."default",
    CONSTRAINT actividades_pkey PRIMARY KEY (id_activity),
    CONSTRAINT actividades_activity_name_key UNIQUE (activity_name)
);
CREATE TABLE IF NOT EXISTS public.canciones (
    id_canciones serial NOT NULL,
    artist_id integer NOT NULL,
    mood_id integer NOT NULL,
    activity_id integer NOT NULL,
    genre_id integer NOT NULL,
    climates_id integer NOT NULL,
    duration integer NOT NULL,
    cancion_name character varying NOT NULL,
    cancion_imagen character varying NOT NULL,
    CONSTRAINT canciones_pkey PRIMARY KEY (id_canciones)
);
CREATE TABLE IF NOT EXISTS public.artistas (
    id_artist serial NOT NULL,
    name_artist character varying COLLATE pg_catalog."default" NOT NULL,
    image_artist character varying COLLATE pg_catalog."default",
    CONSTRAINT artistas_pkey PRIMARY KEY (id_artist),
    CONSTRAINT artistas_artist_name_key UNIQUE (name_artist)
);
CREATE TABLE IF NOT EXISTS public.climas (
    id_climates serial NOT NULL,
    climates_name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT climas_pkey PRIMARY KEY (id_climates),
    CONSTRAINT climas_climates_name_key UNIQUE (climates_name)
);
CREATE TABLE IF NOT EXISTS public.generos (
    id_genre serial NOT NULL,
    genre_name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT generos_pkey PRIMARY KEY (id_genre),
    CONSTRAINT generos_genre_name_key UNIQUE (genre_name)
);
CREATE TABLE IF NOT EXISTS public.estadosdeanimo (
    id_mood SERIAL NOT NULL,
    mood_name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estadosdeanimo_pkey PRIMARY KEY (id_mood),
    CONSTRAINT estadosdeanimo_mood_name_key UNIQUE (mood_name)
);
CREATE TABLE IF NOT EXISTS public.canciones_playlists (
    playlist_id integer NOT NULL,
    canciones_id integer NOT NULL
);
CREATE TABLE IF NOT EXISTS public.playlists (
    id_playlist serial NOT NULL,
    user_id integer NOT NULL,
    name_playlist character varying COLLATE pg_catalog."default",
    CONSTRAINT playlists_pkey PRIMARY KEY (id_playlist)
);
CREATE TABLE IF NOT EXISTS public.usuarios (
    id_users serial NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    username character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_users),
    CONSTRAINT usuarios_email_key UNIQUE (email),
    CONSTRAINT usuarios_username_key UNIQUE (username)
);
ALTER TABLE IF EXISTS public.canciones
ADD CONSTRAINT canciones_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.actividades (id_activity) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public.canciones
ADD CONSTRAINT canciones_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES public.artistas (id_artist) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public.canciones
ADD CONSTRAINT canciones_climates_id_fkey FOREIGN KEY (climates_id) REFERENCES public.climas (id_climates) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public.canciones
ADD CONSTRAINT canciones_genre_id_fkey FOREIGN KEY (genre_id) REFERENCES public.generos (id_genre) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public.canciones
ADD CONSTRAINT canciones_mood_id_fkey FOREIGN KEY (mood_id) REFERENCES public.estadosdeanimo (id_mood) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public.canciones_playlists
ADD CONSTRAINT canciones_playlist_canciones_id_fkey FOREIGN KEY (canciones_id) REFERENCES public.canciones (id_canciones) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public.canciones_playlists
ADD CONSTRAINT canciones_playlist_playlist_id_fkey FOREIGN KEY (playlist_id) REFERENCES public.playlists (id_playlist) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public.playlists
ADD CONSTRAINT playlists_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.usuarios (id_users) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
INSERT INTO public.actividades (activity_name)
VALUES ('Ejercicio Físico'),
    ('Limpieza'),
    ('Celebración'),
    ('Dormir'),
    ('Meditar'),
    ('Social'),
    ('Estudiar'),
    ('Relajación'),
    ('Viajando');
--@block
INSERT INTO public.climas (climates_name)
VALUES ('Frio'),
    ('Calor'),
    ('Lluvia');
--@block
INSERT INTO public.estadosdeanimo (mood_name)
VALUES ('Triste'),
    ('Felíz'),
    ('Fiesta');
--@block
INSERT INTO public.generos (genre_name)
VALUES ('Rock'),
    ('Country'),
    ('Soul'),
    ('Jazz'),
    ('Blues'),
    ('Hip-Hop'),
    ('Pop'),
    ('Reggae'),
    ('Folk'),
    ('R&B'),
    ('Clásico'),
    ('Alternativo'),
    ('Ambiente'),
    ('EDM'),
    ('Electrónica'),
    ('Disco'),
    ('New Age'),
    ('Punk');
--@block
INSERT INTO public.usuarios (email, username, password)
VALUES (
        'usuario1@example.com',
        'usuario1',
        'contraseña1'
    ),
    (
        'usuario2@example.com',
        'usuario2',
        'contraseña2'
    ),
    (
        'usuario3@example.com',
        'usuario3',
        'contraseña3'
    );
--@block
INSERT INTO public.artistas (name_artist, image_artist)
VALUES (
        'Avicii',
        'https://i.scdn.co/image/ab6761610000e5ebae07171f989fb39736674113'
    ),
    (
        'Arcángel',
        'https://i.scdn.co/image/ab6761610000e5ebe963e7ad5259c34a7ca54319'
    ),
    (
        'Rosalía',
        'https://i.scdn.co/image/ab67616d00001e02c76ccdb32228d3ea38a9f5d6'
    ),
    (
        'Post Malone',
        'https://i.scdn.co/image/ab67616d00001e0255404f712deb84d0650a4b41'
    ),
    (
        'Bad Bunny',
        'https://i.scdn.co/image/ab676161000051749ad50e478a469448c6f369df'
    ),
    (
        'Duki',
        'https://i.scdn.co/image/ab6761610000e5eb731bcc0d0f1323fbf91c5719'
    ),
    (
        'Michael Jackson',
        'https://i.scdn.co/image/ab6761610000e5eb0e08ea2c4d6789fbf5cbe0aa'
    ),
    (
        'Ray Charles',
        'https://i.scdn.co/image/ab6761610000e5eb6fc460f10177fa38af69b8bf'
    ),
    (
        'Cuarteto De Nos',
        'https://i.scdn.co/image/ab6761610000e5ebbcd488bfdbb27e3cf2084e47'
    ),
    (
        'Shakira',
        'https://img.gruporeforma.com/imagenes/960x640/6/418/5417226.jpg'
    ),
    (
        'Four Tops',
        'https://i.scdn.co/image/ab67616d0000b27326a15b50daacda177348b874'
    ),
    (
        'Aretha Franklin',
        'https://i.scdn.co/image/ab6761610000e5ebf12270128127ba170f90097d'
    ),
    (
        'Frank Sinatra',
        'https://i.scdn.co/image/ab67616d0000b273b81d66d1416afa139d12767b'
    ),
    (
        'B. B. King',
        'https://i.scdn.co/image/7e53bec2f958fa7fd1868124a0897cb0d08b60ee'
    ),
    (
        'Leadbelly',
        'https://i.scdn.co/image/c2de68356371867b957930529d32c9cc2b9e1580'
    ),
    (
        'Tchaikovsky',
        'https://i.scdn.co/image/9a7c31f43e22a95f6d3c57baf4f87a3a9d2b93e0'
    ),
    (
        'Tycho',
        'https://i.scdn.co/image/ab6761610000e5eb4dc28dcee5516d2e89690525'
    ),
    (
        'Enya',
        'https://i.scdn.co/image/ab6761610000e5eb9ce996547e0b307c94f662e6'
    ),
    (
        'Ramones',
        'https://i.scdn.co/image/ab6761610000e5eb5b9f46a5c5bf8243179d56b0'
    );
--@block
INSERT INTO public.canciones (
        artist_id,
        mood_id,
        activity_id,
        genre_id,
        climates_id,
        duration,
        cancion_name,
        cancion_imagen
    )
VALUES (
        1,
        3,
        3,
        15,
        2,
        230,
        'Waiting For Love',
        'https://images.genius.com/2a23487b6fa9b49fa6f5df1e7e093fdf.1000x1000x1.jpg'
    ),
    (
        2,
        3,
        6,
        6,
        2,
        256,
        'La Jumpa',
        'https://i.scdn.co/image/ab6761610000e5ebe963e7ad5259c34a7ca54319'
    ),
    (
        3,
        1,
        2,
        7,
        3,
        169,
        'Mala Mente',
        'https://i.scdn.co/image/ab67616d00001e02c76ccdb32228d3ea38a9f5d6'
    ),
    (
        4,
        1,
        9,
        6,
        3,
        158,
        'Allergic',
        'https://i.scdn.co/image/ab67616d00001e0250d035b8373ec9df7c5a2ff0'
    ),
    (
        4,
        1,
        7,
        6,
        1,
        227,
        'Circles',
        'https://i.scdn.co/image/ab67616d00001e0255404f712deb84d0650a4b41'
    ),
    (
        3,
        2,
        1,
        7,
        2,
        109,
        'Bizcochito',
        'https://images.genius.com/61f4b60085de904aa28fe4c097d2f8c5.500x500x1.jpg'
    ),
    (
        2,
        2,
        8,
        8,
        1,
        196,
        'Me Prefieres A Mi',
        'https://i.scdn.co/image/ab67616d0000b2739e92bc926b08dd60341148a6'
    ),
    (
        1,
        1,
        5,
        2,
        3,
        272,
        'Wake Me Up',
        'https://i.scdn.co/image/ab67616d00001e025393c5d3cac806092a9bc468'
    ),
    (
        5,
        2,
        3,
        6,
        2,
        266,
        'Monaco',
        'https://i.scdn.co/image/ab67706c0000da849cf0e5e51ffe4225c7eecfee'
    ),
    (
        5,
        1,
        9,
        2,
        3,
        195,
        '1 Porciento',
        'https://i.scdn.co/image/ab67706c0000da84c4a37aaa630a562bbd99cb02'
    ),
    (
        6,
        2,
        1,
        6,
        2,
        217,
        'Hello Cotto',
        'https://i.scdn.co/image/ab67616d0000b2736b43ad890ad0d010e3e2a6d6'
    ),
    (
        6,
        3,
        2,
        12,
        1,
        158,
        'Si Te Sentis Sola',
        'https://i.scdn.co/image/ab67616d00001e0206818149362f4a2bd1d44323'
    ),
    (
        7,
        3,
        3,
        16,
        1,
        328,
        'Thriller',
        'https://i.scdn.co/image/ab67616d0000b27379b8d5f5821bddae3bc5e6a9'
    ),
    (
        7,
        2,
        3,
        7,
        1,
        295,
        'Billie Jean',
        'https://i.scdn.co/image/ab67616d0000b273de437d960dda1ac0a3586d97'
    ),
    (
        8,
        2,
        2,
        3,
        2,
        176,
        'I Got A Woman',
        'https://i.scdn.co/image/ab67616d0000b273b6bc18f4c8db41c00ea25e85'
    ),
    (
        8,
        3,
        3,
        10,
        2,
        139,
        'Hit The Road',
        'https://i.scdn.co/image/ab67616d0000b2731c80d0a392d1673c425ea970'
    ),
    (
        9,
        1,
        5,
        1,
        1,
        237,
        'El Hijo De Hernandez',
        'https://i.scdn.co/image/ab67616d00001e021cf84979a6b7d69db35773ec'
    ),
    (
        9,
        1,
        7,
        1,
        3,
        250,
        'Roberto',
        'https://i.scdn.co/image/ab6761610000e5ebbcd488bfdbb27e3cf2084e47'
    ),
    (
        10,
        3,
        3,
        7,
        2,
        213,
        'Waka Waka',
        'https://i.scdn.co/image/ab67616d0000b2730b1757e4ebde03f45acbd483'
    ),
    (
        10,
        3,
        2,
        2,
        1,
        187,
        'El Jefe',
        'https://i.scdn.co/image/ab67616d0000b2731e45888bd125c016dbe319aa'
    ),
    (
        11,
        2,
        2,
        3,
        2,
        148,
        ' I Cant Help Myself',
        'https://i.scdn.co/image/ab67616d0000b273c0fa62ae53b2aeae3766f13d'
    ),
    (
        11,
        2,
        2,
        3,
        3,
        153,
        'Reach Out Ill Be There',
        'https://i.scdn.co/image/ab67616d0000b273f77ddfd53bdb4b450c311fb9'
    ),
    (
        12,
        2,
        8,
        3,
        2,
        203,
        'I Say a Little Prayer',
        'https://i.scdn.co/image/ab67616d0000b27346c31f64babcbfca6e061b6b'
    ),
    (
        12,
        1,
        7,
        3,
        1,
        212,
        'Call Me',
        'https://i.scdn.co/image/ab67616d0000b273118022639a7119b9cc1872d7'
    ),
    (
        12,
        2,
        2,
        3,
        2,
        137,
        'Respect',
        'https://i.scdn.co/image/ab67616d0000b273d24f7a631e00b00a0e37832c'
    ),
    (
        13,
        2,
        2,
        4,
        3,
        137,
        'Fly Me to the Moon',
        'https://i.scdn.co/image/ab67616d0000b273b19cb81319fbfd9ed54baeae'
    ),
    (
        13,
        1,
        8,
        4,
        3,
        184,
        'My Way of Life',
        'https://lastfm.freetls.fastly.net/i/u/500x500/8ea4bf5ca2644c4e93f962c912c2540b.jpg'
    ),
    (
        14,
        2,
        8,
        5,
        1,
        270,
        'Darlin You Know I Love You',
        'https://i.scdn.co/image/ab67616d0000b273b334695694119beeb870ed17'
    ),
    (
        14,
        2,
        8,
        5,
        1,
        314,
        'The thrill is gone',
        'https://i.scdn.co/image/ab67616d00001e02095a2950c81cb271216a811b'
    ),
    (
        15,
        2,
        2,
        9,
        1,
        190,
        'In New Orleans',
        'https://i.scdn.co/image/ab67616d0000b2736d2cb9088a8a800f7cb41fcb'
    ),
    (
        15,
        2,
        2,
        9,
        2,
        184,
        'Alabama Bound',
        'https://i.scdn.co/image/ab67616d0000b273b00102fc144d521d8168a357'
    ),
    (
        16,
        2,
        7,
        11,
        2,
        388,
        'Vals de las Flores',
        'https://i.scdn.co/image/ab67616d00001e02486aad29c25e4e384608ecd1'
    ),
    (
        16,
        2,
        7,
        11,
        1,
        267,
        'Valse Sentimentale',
        'https://i.scdn.co/image/ab67616d00001e0269cb5fdfa8dde8977a7a3fe6'
    ),
    (
        17,
        2,
        7,
        13,
        2,
        321,
        'Daydream',
        'https://i.scdn.co/image/ab67616d0000b273e3685463e9a139c239030e31'
    ),
    (
        17,
        2,
        7,
        13,
        2,
        246,
        'Outer Sunset',
        'https://i.scdn.co/image/ab67616d0000b273977b0c4c69cf4e6d37724c72'
    ),
    (
        1,
        2,
        3,
        14,
        2,
        187,
        'The Nights',
        'https://i.scdn.co/image/ab67616d00001e02e14f11f796cef9f9a82691a7'
    ),
    (
        18,
        2,
        4,
        17,
        2,
        206,
        'Orinoco',
        'https://i.scdn.co/image/ab67616d00001e02f904999277431f39e3698976'
    ),
    (
        18,
        2,
        8,
        17,
        1,
        142,
        'A Day Without Rain',
        'https://i.scdn.co/image/ab67616d0000b2730798196acd39d8d0387e9a9b'
    ),
    (
        19,
        2,
        1,
        18,
        2,
        142,
        'I Wanna Be Sedated',
        'https://i.scdn.co/image/ab67616d0000b273adde2b42b638269d8c0b017d'
    ),
    (
        19,
        2,
        1,
        18,
        2,
        124,
        'Rockaway Beach',
        'https://i.scdn.co/image/ab67616d0000b27322303b8823306f7a71c84573'
    );
--@block
INSERT INTO public.playlists (user_id, name_playlist)
VALUES (1, 'Primer Playlist'),
    (2, 'Segunda Playlist');
--@block
INSERT INTO public.canciones_playlists (playlist_id, canciones_id)
VALUES (1, 3),
    (2, 2);