-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial,
    email character varying NOT NULL,
    username character varying NOT NULL,
    password character varying NOT NULL,
    CONSTRAINT usuarios_email_key UNIQUE (email),
    CONSTRAINT usuarios_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.actividades
(
    id_activity serial NOT NULL,
    activity_name character varying,
    PRIMARY KEY (id_activity)
);

CREATE TABLE IF NOT EXISTS public.estadosdeanimo
(
    id_mood serial NOT NULL,
    mood_name character varying NOT NULL,
    PRIMARY KEY (id_mood)
);

CREATE TABLE IF NOT EXISTS public.climas
(
    id_climates serial NOT NULL,
    climates_name character varying NOT NULL,
    PRIMARY KEY (id_climates)
);

CREATE TABLE IF NOT EXISTS public.generos
(
    id_genre serial NOT NULL,
    genre_name character varying NOT NULL,
    PRIMARY KEY (id_genre)
);
END;